# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

#添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: Home
    url: /
  archives:
    url: /archives
  github:
    url: https://github.com/nju-cs-flyers/nju-cs-flyers.github.io/issues
    target: _blank

rss: /atom.xml

#你的头像url
avatar: /img/avatar.jpg

#添加图像点击链接，默认为主目录，可根据需要修改about等目录
avatar_link: /

# email
email: nju.cs.flyers@gmail.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#800080'

# Content
tags:
  title: 标签

# 文章截断
excerpt_render: false
excerpt_length: 200
excerpt_link: read more...
mathjax: false
archive_yearly: true

#是否开启分享
share: false

#是否开启打赏，关闭 reward: false
reward: false

#是否开启搜索
search: true

#是否大屏幕下文章页隐藏导航
hideMenu: true

#是否开启toc
#toc: false
toc:
  list_number: true  # 是否显示数字排序

#站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# Miscellaneous
google_analytics: ''
favicon: /img/favicon.png

# less
less:
  compress: true
  paths:
    - source/css/style.less

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
